//******************
// Generated by kivi
//******************

import '../entities/student_entity.dart';

class GetStudentUsecase {
  Future<Student?> call(int studentId) {
    // TODO: implement call
    throw UnimplementedError();
  }
}
