import '../../entities/student_entity.dart';
import '../../usecases/student_usecase.dart';
import '../student_repository.dart';

//******************
// Generated by kivi
//******************

abstract class StudentRepositoryImpl implements StudentRepository {
  final GetStudentUsecase getStudentUseCase;
  StudentRepositoryImpl(this.getStudentUseCase);

  @override
  Future<void> delete(int id) {
    // TODO: implement delete
    throw UnimplementedError();
  }

  Future<List<Student?>> getAll() {
    // TODO: implement getAll
    throw UnimplementedError();
  }

  @override
  Future<void> insert(Student student) {
    // TODO: implement insert
    throw UnimplementedError();
  }

  @override
  Future<void> update(Student student) {
    // TODO: implement update
    throw UnimplementedError();
  }
}
