

//******************
// Generated by kivi
//******************

class Student {
  final String id;
  final String name;
  final String description;

  Student({
    required this.id,
    required this.name,
    required this.description,
  });

  // Constructor for converting a Map into a student Entity
  factory Student.fromMap(Map<String, dynamic> map) {
    return Student(
      id: map['id'],
      name: map['name'],
      description: map['description'],
    );
  }

  // Convert Student Entity instance to Map
  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'name': name,
      'description': description,
    };
  }
}  